Modified Gentoo build workflow.

diff --git a/.github/workflows/emerge.yml b/.github/workflows/emerge.yml
--- a/.github/workflows/emerge.yml
+++ b/.github/workflows/emerge.yml
@@ -1,4 +1,4 @@
-name: "gcc 12 "
+name: "gcc 12.2 "
 
 on:
   pull_request:
@@ -83,6 +83,59 @@ jobs:
           exit 1
         fi
         exit 0
+    - name: CPP Checks
+      if: always()
+      run: |
+        touch cpp_checks.txt
+        for changed_file in ${{ steps.changed-files.outputs.all }}; do
+          if [[ -f $changed_file ]]; then
+            if [[ $changed_file == *.cpp ]]; then
+              bash tools/ci/cpp.sh ${changed_file} 2>> cpp_checks.txt || true
+            fi
+          fi
+        done
+        cat cpp_checks.txt
+        if [ -s cpp_checks.txt ]
+        then
+          exit 1
+        fi
+        exit 0
+# Clang compilation and checks are being omitted for now. Clang 14 is not current on 
+# Gentoo, and using the stage3 docker image would require building the llvm toolchain 
+# (too much time/too many resourches). Considering this verification a low priority.
+#    - name: CPP Formatting Checks
+#      if: always()
+#      run: |
+#        clang-format-14 -version
+#        touch cpp_formatting_checks.txt
+#        for changed_file in ${{ steps.changed-files.outputs.all }}; do
+#          if [[ -f $changed_file ]]; then
+#            if [[ $changed_file == *.cpp || $changed_file == *.h ]]; then
+#              clang-format-14 -style=file -i ${changed_file}
+#            fi
+#          fi
+#        done
+#        git diff --color >> cpp_formatting_checks.txt
+#        git reset --hard
+#        if [ -s cpp_formatting_checks.txt ]
+#        then
+#          echo ""
+#          echo "You have errors in your C++ code formatting."
+#          echo "Please see below in red for the incorrect formatting, and in green for the correct formatting."
+#          echo "You can either fix the formatting by hand or use clang-format."
+#          echo "(You can safely ignore warnings about \$TERM and tput)"
+#          echo ""
+#          cat cpp_formatting_checks.txt | diff-so-fancy || true
+#          exit 1
+#        fi
+#        exit 0
+#    - name: Upload CPP Formatting Diff
+#      if: hashFiles('cpp_formatting_checks.txt') != ''
+#      uses: actions/upload-artifact@v3
+#      with:
+#        name: clang_format_diff
+#        path: |
+#          cpp_formatting_checks.txt
     - name: Lua Checks
       if: always()
       run: |
@@ -139,7 +192,7 @@ jobs:
           exit 1
         fi
         exit 0
-    - name: Configure CMake
+    - name: Configure CMake GCC
       run: |
         export CC=/usr/bin/gcc-12
         export CXX=/usr/bin/g++-12
@@ -148,3 +201,12 @@ jobs:
     - name: Build
       run: |
         cmake --build build -j4
+# See above regarding Clang.
+# - name: Configure CMake Clang
+#      run: |
+#        export CC=/usr/bin/clang-14
+#        export CXX=/usr/bin/clang++-14
+#        cmake -S . -B build
+#    - name: Build
+#      run: |
+#        cmake --build build -j4
