Add character creation etc back to startup check
That's my purse.
I don't know you.

diff --git a/.github/workflows/emerge-dirty.yml b/.github/workflows/emerge-dirty.yml
--- a/.github/workflows/emerge-dirty.yml
+++ b/.github/workflows/emerge-dirty.yml
@@ -399,6 +399,15 @@ jobs:
       run: |
         sed -i -e 's/SQL_HOST     = "127.0.0.1"/SQL_HOST     = "mysql"/g' settings/default/network.lua
         cp settings/default/* settings/
+    - name: Enable Modules
+      shell: bash
+      run: |
+        python3 << EOF
+        with open("modules/init.txt", "w") as f:
+            f.write("custom\n")
+            f.write("era\n")
+            f.write("renamer\n")
+        EOF
     - name: Startup checks
       run: |
          chmod +x xi_connect
@@ -417,6 +426,91 @@ jobs:
           screen -d -m -S xi_map ./xi_map --log map-server-0.log --ip 127.0.0.1 --port 54230
           screen -d -m -S xi_map ./xi_map --log map-server-1.log --ip 127.0.0.1 --port 54231
           screen -d -m -S xi_world ./xi_world --log world-server.log
+
+          # define bash helper function to help diagnose any sql errors
+          function mysqlcmd() { mysql xidb -h 127.0.0.1 -uroot -proot --verbose -e "$@"; }
+          printf "\nPopulating database\n"
+
+          # Clean out anything already there (just in case)
+          mysqlcmd "DELETE FROM accounts;"
+          mysqlcmd "DELETE FROM chars;"
+          mysqlcmd "DELETE FROM char_look;"
+          mysqlcmd "DELETE FROM char_stats;"
+
+          # Clean tables that are made from triggers on insert to char table
+          mysqlcmd "DELETE FROM char_equip;"
+          mysqlcmd "DELETE FROM char_exp;"
+          mysqlcmd "DELETE FROM char_history;"
+          mysqlcmd "DELETE FROM char_inventory;"
+          mysqlcmd "DELETE FROM char_jobs;"
+          mysqlcmd "DELETE FROM char_pet;"
+          mysqlcmd "DELETE FROM char_points;"
+          mysqlcmd "DELETE FROM char_profile;"
+          mysqlcmd "DELETE FROM char_storage;"
+          mysqlcmd "DELETE FROM char_unlocks;"
+
+          # Create an account
+          mysqlcmd "INSERT INTO accounts (id, login, password, timecreate, timelastmodify, status, priv)
+          VALUES(1000, 'admin', PASSWORD('admin'), NOW(), NOW(), 1, 1);
+          SELECT id, login, content_ids FROM accounts;"
+
+          # Create a character
+          mysqlcmd "INSERT INTO chars (charid, accid, charname, pos_zone, nation, gmlevel)
+          VALUES(1, 1000, 'Test', 0, 0, 5);
+          SELECT charid, accid, charname, pos_zone FROM chars;"
+
+          # Set char_look (default is 0 and trips up scripting)
+          mysqlcmd "INSERT INTO char_look (charid, face, race, size, head, body, hands, legs, feet, main, sub, ranged)
+          VALUES (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1);
+          SELECT charid, face, race FROM char_look;"
+
+          # Populate more char tables with defaults
+          mysqlcmd "INSERT INTO char_stats (charid, mjob)
+          VALUES(1, 1);
+          SELECT charid, mjob FROM char_stats;"
+
+          # Update character information
+          # Place near some Robber Crabs in Kuftal Tunnel
+          mysqlcmd "UPDATE chars
+          SET
+              pos_zone = 174,
+              pos_prevzone = 174,
+              pos_x = 55,
+              pos_y = -9,
+              pos_z = -140
+          WHERE charid = 1;"
+
+          mysqlcmd "SELECT charid, accid, charname, pos_zone, pos_x, pos_y, pos_z FROM chars;"
+          # Set GodMode CharVar = 1
+          mysqlcmd "INSERT INTO char_vars(charid, varname, value)
+          VALUES(1, 'GodMode', 1);"
+
+          printf "\nRunning HeadlessXI for 60 seconds\n"
+          python3 << EOF
+          import time
+          try:
+              from tools.headlessxi.hxiclient import HXIClient
+              hxi_client = HXIClient('admin', 'admin', 'localhost')
+              hxi_client.login()
+              print('Sleeping 60s')
+              time.sleep(60)
+              hxi_client.logout()
+              exit(0)
+          except Exception as e:
+              exit(-1)
+          EOF
+          hxi_result=$?
+
+          pkill -SIGINT xi_map
+          pkill -SIGINT xi_search
+          pkill -SIGINT xi_connect
+          pkill -SIGINT xi_world
+
+          # fail if hxi had a non-zero exit code
+          if [[ "$hxi_result" -ne "0" ]]; then
+              echo "hxi exited with code $hxi_result"
+              exit $hxi_result
+          fi
     - name: Check for errors and warnings
       if: ${{ success() || failure() }}
       run: |
